/** @type {import('tailwindcss').Config} */
const plugin = require("tailwindcss/plugin");
export default {
  content: ["./src/**/*.{html,js}"],
  theme: {
    fontFamily: {
      primary: ["var(--font-primary)"],
      paragraph: ["var(--font-paragraph)"],
      heading: ["var(--font-heading)"],
    },
    borderRadius: {
      xl: "var(--xl-px)",
      lg: "var(--lg-px)",
      md: "var(--md-px)",
      sm: "var(--sm-px)",
      xs: "var(--xs-px)",
    },
    colors: {
      primary: "var(--ion-color-primary)",
      secondary: "var(--ion-color-secondary)",
      tertiary: "var(--ion-color-tertiary)",
      success: "var(--ion-color-success)",
      warning: "var(--ion-color-warning)",
      danger: "var(--ion-color-danger)",
      light: "var(--ion-color-light)",
      medium: "var(--ion-color-medium)",
      dark: "var(--ion-color-dark)",

      black: "var(--color-black)",
      white: "var(--color-white)",
      paragraph: "var(--ion-text-color)",
      heading: "var(--ion-text-color)",
      link: "var(--ion-link-color)",

      black: {
        0: "var(--color-black)",
        10: "var(--color-black-10)",
        100: "var(--color-black-100)",
        200: "var(--color-black-200)",
        300: "var(--color-black-300)",
      },
      yellow: {
        100: "var(--color-yellow-100)",
        200: "var(--color-yellow-200)",
      },
      green: {
        100: "var(--color-green-100)",
        200: "var(--color-green-200)",
      },
      red: {
        100: "var(--color-red-100)",
        200: "var(--color-red-200)",
        300: "var(--color-red-300)",
      },
    },
    screens: {
      uhd: { raw: "(max-width: 3840px)" },
      qhd: { raw: "(max-width: 2560px)" },
      fhd: { raw: "(max-width: 1920px)" },
      "2xl": { raw: "(max-width: 1536px)" },
      xl: { raw: "(max-width: 1366px)" },
      mobile: { raw: "(max-width: 1040px)" },
      lg: { raw: "(max-width: 1024px)" },
      md: { raw: "(max-width: 768px)" },
      sm: { raw: "(max-width: 640px)" },
      xs: { raw: "(max-width: 480px)" },
      xss: { raw: "(max-width: 380px)" },

      "uhd-min": { raw: "(min-width: 3841px)" },
      "qhd-min": { raw: "(min-width: 2561px)" },
      "fhd-min": { raw: "(min-width: 1921px)" },
      "2xl-min": { raw: "(min-width: 1537px)" },
      "xl-min": { raw: "(min-width: 1367px)" },
      "desktop-min": { raw: "(min-width: 1041px)" },
      "lg-min": { raw: "(min-width: 1025px)" },
      "md-min": { raw: "(min-width: 769px)" },
      "sm-min": { raw: "(min-width: 641px)" },
      "xs-min": { raw: "(min-width: 481px)" },
      "xss-min": { raw: "(min-width: 381px)" },

      "v-700": { raw: "(max-height: 700px) and (max-width: 1024px)" },
    },
    extend: {
      containers: {
        "5xl": "3840px",
        "4xl": "2560px",
        "3xl": "1920px",
        "2xl": "1536px",
        xl: "1366px",
        desktop: "1080px", // 1040 + 2 * 20
        lg: "1024px",
        md: "768px",
        sm: "640px",
        xs: "480px",
      },
      aspectRatio: {
        // "image-sm": "var(--aspect-ratio-image-sm)",
        // "image-md": "var(--aspect-ratio-image-md)",
        // "image-lg": "var(--aspect-ratio-image-lg)",
      },
      spacing: {
        1: "10px",
        2: "20px",
        3: "30px",
        4: "40px",
        5: "50px",
        6: "60px",
        7: "70px",
        8: "80px",
        9: "90px",
        10: "100px",
        11: "110px",
        12: "120px",
        13: "130px",
        14: "140px",
        15: "150px",
        16: "160px",
        17: "170px",
        18: "180px",
        19: "190px",
        20: "200px",
        25: "250px",
        30: "300px",
        40: "400px",
        50: "500px",
        60: "600px",
        70: "700px",
        80: "800px",
        90: "900px",
        desktop: "1080px",
        "7xl": "var(--7xl-px)",
        "6xl": "var(--6xl-px)",
        "5xl": "var(--5xl-px)",
        "4xl": "var(--4xl-px)",
        "3xl": "var(--3xl-px)",
        "2xl": "var(--2xl-px)",
        xl: "var(--xl-px)",
        lg: "var(--lg-px)",
        md: "var(--md-px)",
        sm: "var(--sm-px)",
        xs: "var(--xs-px)",
      },
      gap: {
        1: "10px",
        2: "20px",
        3: "30px",
        4: "40px",
        5: "50px",
        6: "60px",
        7: "70px",
        8: "80px",
        9: "90px",
        10: "100px",
        11: "110px",
        12: "120px",
        13: "130px",
        14: "140px",
        15: "150px",
        16: "160px",
        17: "170px",
        18: "180px",
        19: "190px",
        20: "200px",
        xl: "var(--xl-px)",
        lg: "var(--lg-px)",
        md: "var(--md-px)",
        sm: "var(--sm-px)",
        xs: "var(--xs-px)",
      },
      fontSize: {
        1: "10px",
        2: "20px",
        3: "30px",
        4: "40px",
        5: "50px",
        6: "60px",
        7: "70px",
        8: "80px",
        9: "90px",
        10: "100px",
        11: "110px",
        12: "120px",
        13: "130px",
        14: "140px",
        15: "150px",
        16: "160px",
        17: "170px",
        18: "180px",
        19: "190px",
        20: "200px",
        "2xl": "var(--2xl-px)",
        xl: "var(--xl-px)",
        lg: "var(--lg-px)",
        md: "var(--md-px)",
        sm: "var(--sm-px)",
        xs: "var(--xs-px)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/container-queries"),
    plugin(function ({ addVariant }) {
      addVariant("children", "&>*");
    }),
  ],
};
